# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestovoeAvito' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestovoeAvito

  target 'TestovoeAvitoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestovoeAvitoUITests' do
    # Pods for testing
  end

  pod 'SnapKit', '~> 5.0.0'
  
  pod 'SwiftyJSON', '~> 4.0'

end
